# Generated by Django 5.0.1 on 2024-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutapp', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='person_images'),
        ),
    ]
