# Generated by Django 5.0.1 on 2024-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutapp', '0003_experience_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='image2',
        ),
    ]
