# Generated by Django 5.0.1 on 2024-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutapp', '0004_image_remove_experience_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image2',
        ),
    ]
