# Generated by Django 5.0.6 on 2024-09-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutapp', '0006_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
