# Generated by Django 5.0.1 on 2024-03-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_images')),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('datawars', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('skill_01', models.CharField(max_length=200)),
                ('skill_02', models.CharField(max_length=200)),
                ('skill_03', models.CharField(max_length=200)),
                ('skill_04', models.CharField(max_length=200)),
                ('skill_05', models.CharField(max_length=200)),
                ('skill_06', models.CharField(max_length=200)),
                ('skill_07', models.CharField(max_length=200)),
                ('skill_08', models.CharField(max_length=200)),
                ('skill_09', models.CharField(max_length=200)),
                ('skill_10', models.CharField(max_length=200)),
                ('skill_11', models.CharField(max_length=200)),
                ('skill_12', models.CharField(max_length=200)),
                ('skill_13', models.CharField(max_length=200)),
            ],
        ),
    ]
