# Generated by Django 5.0.1 on 2024-03-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_skill_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_2', models.CharField(max_length=200)),
                ('skill_27', models.CharField(max_length=200)),
                ('skill_28', models.CharField(max_length=200)),
                ('skill_29', models.CharField(max_length=200)),
                ('skill_30', models.CharField(max_length=200)),
                ('skill_31', models.CharField(max_length=200)),
                ('skill_32', models.CharField(max_length=200)),
                ('skill_33', models.CharField(max_length=200)),
                ('skill_34', models.CharField(max_length=200)),
                ('skill_35', models.CharField(max_length=200)),
                ('skill_36', models.CharField(max_length=200)),
                ('skill_37', models.CharField(max_length=200)),
                ('skill_38', models.CharField(max_length=200)),
                ('skill_39', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_3', models.CharField(max_length=200)),
                ('skill_40', models.CharField(max_length=200)),
                ('skill_41', models.CharField(max_length=200)),
                ('skill_42', models.CharField(max_length=200)),
                ('skill_43', models.CharField(max_length=200)),
                ('skill_44', models.CharField(max_length=200)),
                ('skill_45', models.CharField(max_length=200)),
                ('skill_46', models.CharField(max_length=200)),
                ('skill_47', models.CharField(max_length=200)),
                ('skill_48', models.CharField(max_length=200)),
                ('skill_49', models.CharField(max_length=200)),
                ('skill_50', models.CharField(max_length=200)),
                ('skill_51', models.CharField(max_length=200)),
                ('skill_52', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_4', models.CharField(max_length=200)),
                ('skill_53', models.CharField(max_length=200)),
                ('skill_54', models.CharField(max_length=200)),
                ('skill_55', models.CharField(max_length=200)),
                ('skill_56', models.CharField(max_length=200)),
                ('skill_57', models.CharField(max_length=200)),
                ('skill_58', models.CharField(max_length=200)),
                ('skill_59', models.CharField(max_length=200)),
                ('skill_60', models.CharField(max_length=200)),
                ('skill_61', models.CharField(max_length=200)),
                ('skill_62', models.CharField(max_length=200)),
                ('skill_63', models.CharField(max_length=200)),
                ('skill_64', models.CharField(max_length=200)),
                ('skill_65', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_5', models.CharField(max_length=200)),
                ('skill_66', models.CharField(max_length=200)),
                ('skill_67', models.CharField(max_length=200)),
                ('skill_68', models.CharField(max_length=200)),
                ('skill_69', models.CharField(max_length=200)),
                ('skill_70', models.CharField(max_length=200)),
                ('skill_71', models.CharField(max_length=200)),
                ('skill_72', models.CharField(max_length=200)),
                ('skill_73', models.CharField(max_length=200)),
                ('skill_74', models.CharField(max_length=200)),
                ('skill_75', models.CharField(max_length=200)),
                ('skill_76', models.CharField(max_length=200)),
                ('skill_77', models.CharField(max_length=200)),
                ('skill_78', models.CharField(max_length=200)),
            ],
        ),
    ]
