# Generated by Django 5.0.1 on 2024-03-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_skill_2_skill_3_skill_4_skill_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='works_images/')),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
