# Generated by Django 5.0.1 on 2024-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_0',
            name='skill_01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_02',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_03',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_04',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_05',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_06',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_07',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_08',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_09',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_0',
            name='skill_13',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
