# Generated by Django 5.0.1 on 2024-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0005_alter_skill_0_skill_01_alter_skill_0_skill_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_1',
            name='heading_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_14',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_15',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_16',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_17',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_18',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_19',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_20',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_21',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_22',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_23',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_24',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_25',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_1',
            name='skill_26',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_27',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_28',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_29',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_30',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_31',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_32',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_33',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_34',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_35',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_36',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_37',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_38',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_2',
            name='skill_39',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_40',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_41',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_42',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_43',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_44',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_45',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_46',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_47',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_48',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_49',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_50',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_51',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_3',
            name='skill_52',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_53',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_54',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_55',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_56',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_57',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_58',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_59',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_60',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_61',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_62',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_63',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_64',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_4',
            name='skill_65',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_66',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_67',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_68',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_69',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_70',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_71',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_72',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_73',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_74',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_75',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_76',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_77',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill_5',
            name='skill_78',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
