# Generated by Django 5.0.1 on 2024-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_image_1', models.ImageField(upload_to='project_images')),
                ('project_image_2', models.ImageField(upload_to='project_images')),
                ('technology_used', models.CharField(max_length=200)),
                ('video', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('features', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('project_heading', models.CharField(max_length=200)),
                ('working', models.TextField()),
            ],
        ),
    ]
