# Generated by Django 5.0.1 on 2024-03-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_form',
        ),
    ]
